name: ZooVision_Experiment

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: sqlite:///mlflow.db
    
    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        # Tambahkan tensorboard agar autolog tidak error
        pip install mlflow tensorflow tensorboard streamlit gdown pillow numpy google-api-python-client google-auth-oauthlib google-auth-httplib2
    
    - name: Run mlflow project
      run: |
        # 1. Re-install/Verify mlflow di langkah yang sama
        pip install mlflow tensorflow

        # 2. Jalankan server MLflow di background menggunakan python -m
        python -m mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts --host 127.0.0.1 --port 5000 &
        
        # 3. Tunggu server siap
        sleep 10
        
        # 4. Jalankan project
        export MLFLOW_TRACKING_URI=http://localhost:5000
        python -m mlflow run MLProject --experiment-name "Animal_Classification_Autolog" --env-manager local \
          -P train_path=Dataset-Final/train/ -P f1=64 -P u=64 -P lr=0.0001
    
    - name: Get latest MLflow run_id
      id: get_id
      run: |
        # Python akan otomatis membaca env MLFLOW_TRACKING_URI dari job level
        RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs(experiment_names=['Mengerjakan-Submision-DL'], order_by=['start_time DESC'], max_results=1)['run_id'][0])")
        echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Upload to Google Drive
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      run: |
        python upload_to_gdrive.py --run_id $MLFLOW_RUN_ID

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/submision-dicoding:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/submision-dicoding:latest
